# Generated by Django 6.0.5 on 2026-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AddField(
            model_name='student',
            name='avatar_emoji',
            field=models.CharField(choices=[('🥋', '🥋 Дзюдо'), ('💪', '💪 Сила'), ('🔥', '🔥 Огонь'), ('⚡', '⚡ Молния'), ('🦁', '🦁 Лев'), ('🐺', '🐺 Волк'), ('🐯', '🐯 Тигр'), ('🦅', '🦅 Орёл'), ('🐻', '🐻 Медведь'), ('🛡️', '🛡️ Щит'), ('⚔️', '⚔️ Мечи'), ('🏆', '🏆 Кубок'), ('🥇', '🥇 Золото'), ('🥈', '🥈 Серебро'), ('🥉', '🥉 Бронза'), ('🎯', '🎯 Цель'), ('🚀', '🚀 Ракета'), ('🌪️', '🌪️ Вихрь'), ('🧠', '🧠 Ум'), ('🗿', '🗿 Стойкость'), ('🏋️', '🏋️ Силач'), ('🤼', '🤼 Борьба'), ('🏃', '🏃 Скорость'), ('🧗', '🧗 Упорство'), ('🥊', '🥊 Боец'), ('👊', '👊 Удар'), ('✊', '✊ Характер'), ('🤜', '🤜 Напор'), ('🤛', '🤛 Ответ'), ('🦾', '🦾 Железная рука'), ('😤', '😤 Настрой'), ('😎', '😎 Уверенность'), ('🧘', '🧘 Самоконтроль'), ('🌟', '🌟 Звезда'), ('💎', '💎 Алмаз'), ('👑', '👑 Король')], default='🥋', max_length=10, verbose_name='Аватар'),
        ),
    ]
